name: Django-app workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run:
          # update pip
          python -m pip install --upgrade pip
          # install flake8 and plugins
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          # install dependencies
          pip install -r requirements.txt

      - name: Test with flake8 and django tests
        run:
          # run flake8 checking project 
          python -m flake8
